#################################################
#                                               #
#             TNT-Run BY POLLOGAMER             #
#                                               #
#################################################

mapa: 'nombre'
minplayers: 8

pvprun: false

locations:
  lobby:
  spawn: