###############################################
#                                             #
#                 SIRCRAKED FFA               #
#                                             #
###############################################


spawns:
  ffa:
  buildffa:
  comboffa: