#################################################
#                                               #
#             TNT-TAG BY POLLOGAMER             #
#                                               #
#################################################

mapa: 'nombre'
minplayers: 8

locations:
  lobby:
  spawn: